Graph-Learning-Benchmarks/gli

glb/task.py

Bug fix: remove `ClassificationTask` from KG task heritage to prevent `test_dataloading.py` failure.
Keep `num_relations` key in knowledge graph tasks, and create standalone (inherit base class only) task configuration for KG tasks to prevent conflict with `test_dataloading.py`.

Bug fix: remove `ClassificationTask` from KG task heritage.

---

gli/graph.py

Previously, the graph dataset loading will assign all graph labels to each single graph. This pr fixed this bug to the expected behavior: only assign the corresponding graph label to a given graph.
Fixed #271

Fix GraphClassification bug

---

examples/ogbg-molhiv/urls.json
examples/ogbl-collab/urls.json
examples/ogbn-mag/urls.json

Remove the redundant folders in `/examples` that are mistakenly introduced when merging a conflict (in #253).

remove redundant folders in examples

---

CONTRIBUTING.md

Remove the deprecated dropbox link in the instructions on Uploading GLI Data Files in CONTRIBUTING.md. Now asking the contributors host data files on their own cloud storage. Later we may figure out a better solution for data uploading.
#293

change instructions on Uploading GLI Data Files

---

Makefile

Now, `make pytest` can run tests on a single dataset. Example:
```text
$ make pytest DATASET=citeseer
mkdir -p temp
pytest -v tests/ | tee logs/pytest.log
============================= test session starts ==============================
platform darwin -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0 -- /Users/jimmy/miniforge3/envs/gli/bin/python3.8
cachedir: .pytest_cache
rootdir: /Users/jimmy/Projects/Private/gli
collecting ... collected 6 items
tests/test_data_loading.py::test_data_loading[citeseer] PASSED           [ 16%]
tests/test_files.py::test_if_has_essential_files[citeseer] PASSED        [ 33%]
tests/test_kg_training.py::test_relation_prediction[citeseer] PASSED     [ 50%]
tests/test_kg_training.py::test_entity_prediction[citeseer] PASSED       [ 66%] …
```

Update Makefile to allow test single dataset

---

benchmarks/GraphClassification/train.py
benchmarks/GraphClassification/utils.py
benchmarks/NodeClassification/train.py
benchmarks/NodeClassification/train_minibatch.py
benchmarks/NodeClassification/utils.py
datasets/ogbn-proteins/task_node_classification_1.json

To fix https://github.com/Graph-Learning-Benchmarks/gli/issues/285, when `early_stopping` in `train.yaml` is set to `false`.
In such cases, we still store the model when validation accuracy is highest. But no early stopping is applied.
Training is smooth on both graph classification and node classification

Fix early stopping

---

.github/workflows/pytest.yml
datasets/ogbn-proteins/task_node_classification_1.json

This is to fix https://github.com/Graph-Learning-Benchmarks/gli/issues/278, where pytest fails when a dataset is deleted.
The correctness can be verified by https://github.com/Graph-Learning-Benchmarks/gli/pull/328. We delete `cora` completely and testing is successful.
After this PR is merged, https://github.com/Graph-Learning-Benchmarks/gli/pull/328 will be closed.

Fix pytest failure when deleting dataset

---

.github/workflows/pytest.yml

Fix the bug that no test is run (https://github.com/Graph-Learning-Benchmarks/gli/pull/330)
The correctness is verified in https://github.com/Graph-Learning-Benchmarks/gli/pull/333
@jiaqima We can merge this PR so https://github.com/Graph-Learning-Benchmarks/gli/pull/330 will not be blocked.
After this PR is merged, https://github.com/Graph-Learning-Benchmarks/gli/pull/333 will be closed.

fix_no_test_bug

---

datasets/cora/cora.ipynb
datasets/cora/metadata.json
datasets/cora/urls.json
gli/graph.py
gli/task.py
gli/utils.py
tests/test_metadata.py
tests/utils.py

This pull request
- Add a utility function `save_date` for users to safely save multiple arrays.
```python
from gli.utils import save_data
data = {
"node_feats": node_feats,
"node_class": node_class,
"edge": edge,
"node_list": node_list,
"edge_list": edge_list
}
save_data("cora", **data)
```
```
Save all dense arrays to cora.npz, including ['node_class', 'edge', 'node_list', 'edge_list']
Save sparse matrix node_feats to cora_node_feats.sparse.npz
```
- Update the utility function `load_data` for gli to safely load array(s) from file.
- Update cora as an example for dataset saving and loading.
#264 
Fix #266 
See https://github.com/Graph-Learning-Benchmarks/gli/issues/266#issuecomment-1258898577
I only tested this feature on the aforementioned updated version of cora dataset. This PR will …

Use safe save/load method for arrays.

---

datasets/actor/README.md
datasets/arxiv-year/README.md
datasets/chameleon/README.md
datasets/cifar/LICENSE
datasets/cifar/README.md
datasets/citeseer/LICENSE
datasets/citeseer/README.md
datasets/cornell/README.md
datasets/genius/README.md
datasets/mnist/LICENSE
datasets/mnist/README.md

Add LICENSE files to 8 datasets. 
The LICENSE file corresponds to the license of the "Current Version" source stated in README.md. If there is no license presented in that source, an empty LICENSE file is added, in order to pass the file test updated in PR #370. 
This PR also adds the link to the web page and the LICENSE for each version of the datasets listed in README.md. If there is a license for a certain version of the dataset, the license type and the link to the original license is presented. If there is no license found for a certain version of the dataset, "LICENSE: missing" is marked.
#327
Adding LICENSE to each of the dataset hosted in GLI turns to be a complicated task. 
First, there are many commonly used datasets that do not have a license, for all versions. 
Second, there …

add LICENSE files and update README.md in 8 datasets

---

gli/utils.py

`load_data()` will ignore non-numerical arrays.
None
#381

Ignore reading non numeric array

---

tests/preprocess.py

No need to use tests/preprocess.py to download the combined datasets file as we've switched from Google Drive back to Dropbox (#363, #367, #378, #380, #381) so the download limit is no longer an issue for now. This code is still kept in case that we reached the download limit of Dropbox in the future.

do not use test preprocess

---

.pylintrc
gli/utils.py

As titled.
https://github.com/Graph-Learning-Benchmarks/gli/actions/runs/4109270662/jobs/7091223333
https://stackoverflow.com/questions/75370815/pylint-specifying-exception-names-in-the-overgeneral-exceptions-option-without
Tested on my local machine.

Fix pylint test error due to deprecated feature

---

.github/workflows/doc.yml
.github/workflows/pytest.yml

This PR updates our GitHub Action's python version to 3.7. In specific, only the pytest workflow is affected.
See https://github.com/Graph-Learning-Benchmarks/gli/pull/420#issuecomment-1477202977
Test online by GitHub Action.

Upgrade GitHub Action python version to 3.7

---

gli/io.py
gli/utils.py

Add a helper function to help dataset contributors to save the data files and automatically create the `metadata.json` file.
Added an `io.py` to implement helper functions that help dataset contributors to create datasets in GLI formats. In this PR, we implemented a `save_graph` function to save .npz data files of the graph data and automatically create the `metadata.json` file. Currently only homogeneous graphs are supported. 
Also added an `Attribute` class to help guide contributors provide necessary information when adding an attribute to a node, an edge, or a graph. 
This PR is partly adapted from PR #430 by @wood-ghost.
Previously both metadata.json and task json files require the contributors to manually create, which is cumbersome. The new helper functions will significantly ease …

Implement save_graph for homogeneous graphs

---

gli/io.py

Add two helper functions to help dataset contributors to save `NodeRegression` and `NodeClassification` tasks in GLI format.
Added two functions, `save_task_node_regression` and `save_task_node_classification` to save the data splits into data files and automatically create task json files.
See more context in PR #431.
Tested on cora dataset with the following code.
```python
import numpy as np
from dgl.data import CoraGraphDataset
dataset = CoraGraphDataset()
graph = dataset[0]
train_set = graph.ndata["train_mask"].nonzero().squeeze().numpy()
val_set = graph.ndata["val_mask"].nonzero().squeeze().numpy()
test_set = graph.ndata["test_mask"].nonzero().squeeze().numpy()
from gli.io import save_task_node_classification
save_task_node_classification(
name="cora",
description="Node …
```

Add save_task_node_regression and save_task_node_classification

---

.gitignore
gli/config.py
gli/utils.py

Now `download_data()` in `gli.utils` gets url from server first.
#425 
Deleted `urls.json` of cifar dataset, and the url is still downloaded succesfully from EC2 server.

Add url download from server

---

.github/workflows/pylint.yml

The new pylint 3.0.1 will cause some weird stack overflow error. This PR modified the pylint.yml file to force the pylint version to be 2.17.5 to temporarily fix the issue.
Error log of pylint 3.0.1 for future reference:
```
Run pylint $(git ls-files '*.py') --rcfile .pylintrc
Fatal Python error: Cannot recover from stack overflow.
Python runtime state: initialized
Current thread 0x00007f9dd7fa6b[8](https://github.com/Graph-Learning-Benchmarks/gli/actions/runs/6600192279/job/17929956732?pr=455#step:5:9)0 (most recent call first):
File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/astroid/context.py", line 130 in clone
File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/astroid/context.py", line 186 in copy_context
File …
```

fix pylint version to 2.17.5

---

gli/io.py

This PR adds a new rule in `_verify_attrs()`. In particular, we force the provided attributes to be `gli.io.Attribute`. 
None.
When contributing to gli, contributors may not realize the inputs for `node_attrs`, `edge_attrs`, or `graph_attrs` should be a list of `gli.io.Attribute`. Instead, user may provide a list of numpy arrays. We want an explicit error to indicate this requirement.
Tested during developing #454.

Add new rule in _verify_attrs

---

tests/test_files.py
tests/utils.py

`urls.json` will be deprecated. This PR moves missing `urls.json` from error to warning in `test_files.py`. 
This PR also fixed a few docstring typos in `tests/utils.py`.
See #425

move missing urls.json to warning instead of error

---

datasets/cora/cora.ipynb
datasets/cora/metadata.json
datasets/cora/task_node_classification_1.json
datasets/cora/urls.json

This PR uses the new helper function `gli.io.save_graph()` and `save_task_node_classification()` to save CORA dataset. These new functions will be encouraged to use rather than saving manually.
- cora.ipynb: Replace the old saving method by the aforementioned new functions.
- *.json: Generated automatically.
First step of #437. We will update other datasets as well in the near future.
We would like to provide a more clean and user-friendly interface for dataset contribution.
Tested locally shown in the cora.ipynb.

Use new io for dataset saving

---

gli/task.py

PR #450 added the `predict_tail` parameter in the `KGEntityPrediction ` task. However, the existing KG datasets task configuration files did not have this parameter, which leads to an error in data loading. This PR temporarily makes this parameter as optional and sets the default value to be True. This change should be reverted back after all the datasets are updated with the save_task helper function. 
Tested loading FB13.

temporary fix predict_tail missing in existing datasets

---

README.md

`wget` is called during downloading data files, which leads to an error for users who don't have `wget` installed. This PR adds a note in README to remind the user about the dependency on `wget`.
There is a relevant PR #467 but somehow the commit got stuck there. Using this new PR to replace it.

add note for wget

---

gli/io/edge_task.py
gli/io/utils.py

When saving datatset splits like `train_set`, we now use dtype of np.int64 for an consistent behavior with torch, as torch indexing requires long tensor for some version.
This pr fixes #474
This pr is motivated by the issue found in #472.
See automated tests.

Change default int dtype to np.int64 in `gli.io`
