glb/utils.py
Add the google drive downloader from torchvision to improve the data downloading stability.
Tested locally that it can successfully download wiki.npz from the google drive link in PR #246.
=> add google drive downloader

glb/utils.py
Fix the bug in `_download` where the arguments to google drive downloader have the wrong order.
=> fix download arguments mistake

.github/workflows/pytest.yml, tests/preprocess.py
Solve the quota limit problem of google drive by a preprocess for tests. 
See https://github.com/Graph-Learning-Benchmarks/gli/pull/246#issuecomment-1228043088
Tested locally.
=> add preprocess for tests

tests/preprocess.py
Fix the datafiles.tar file in tests/preprocess.py
Test bug introduced in #250 and blocking #253.
=> fix datafiles.tar

FORMAT.md, examples/template/README.md, examples/template/metadata.hjson, examples/template/preprocess.ipynb, examples/template/task_graph_classification.hjson, examples/template/task_kg_entity_prediction.hjson, examples/template/task_kg_relation_prediction.hjson, examples/template/task_link_prediction.hjson, examples/template/task_node_classification.hjson, examples/template/task_time_dependent_link_prediction.hjson
Create a template folder for contributors' reference.
To fix #98
We want users can refer to a concise template when writing their configuration files. This should be ideally like a GitHub Pull Request/Issue template.
Not tested yet.
=> Create template folder

examples/template/README.md
Correct the citation location in the template README.
=> Fix citation location

benchmarks/NodeClassification/train.py, benchmarks/NodeClassification/utils.py
When the `num_classes` attribute from the dataset's `task` file is `2`. Use ROC AUC for evaluation function
Currently we have for dataset whose class number is 2: twitch-gamers, genius, pokec and penn94.  Training is successful on these datasets.
=> update rocauc for binary classification

datasets/arxiv-year/task_node_classification_1.json
Fix the number of classes in arxiv-year from 5 to 2.
=> fix num class in arxiv-year

datasets/arxiv-year/task_node_classification_1.json
Reverts Graph-Learning-Benchmarks/gli#286
=> Revert "fix num class in arxiv-year"

datasets/twitch-gamers/task_node_classification_1.json
Fix twitch-gamer number of classes.
=> fix twitch

benchmarks/NodeClassification/configs/LINKX.yaml, benchmarks/NodeClassification/configs/LINKX_train.yaml, benchmarks/NodeClassification/configs/MixHop.yaml, benchmarks/NodeClassification/configs/train_default.yaml, benchmarks/NodeClassification/train.py, benchmarks/NodeClassification/utils.py
Fix train.py traning_default.yaml and util.py to fit the lim's code.
I have run it on the google cloud. All datasets can be run.
=> Fixing train.py to lim's code

datasets/FB13/README.md, datasets/FB15K/README.md, datasets/FB15K237/README.md, datasets/WN11/README.md, datasets/WN18/README.md, datasets/WN18RR/README.md, datasets/YAGO3-10/README.md
Add and correct citations for OpenKE datasets under datasets/.
Use citations of original sources and previous versions to better document the development of a dataset, and to award the authors of the intermediate works.
=> Update the citations in OpenKE datasets.

benchmarks/GraphClassification/train.py
=> fix device confilct when training on gpu

datasets/ogbn-arxiv/metadata.json, datasets/ogbn-arxiv/ogbn-arxiv.ipynb, datasets/ogbn-arxiv/task_node_classification_1.json, datasets/ogbn-proteins/task_node_classification_1.json
- Update Jupiter notebook of ogbn datasets
- Change target of ogbn-arxiv to nodelabel
=> Change target of ogbn-arxiv

datasets/ogbn-proteins/task_node_classification_1.json
=> Fix ogbn proteins

datasets/ogbn-proteins/task_node_classification_1.json
=> fix ogbn proteins class_num bug

benchmarks/GraphClassification/utils.py, benchmarks/NodeClassification/train.py, benchmarks/NodeClassification/utils.py
Enable training on ogbn-products and ogbn-arxiv.
=> Node multi label

FORMAT.md, gli/graph.py
Fixes #201
- Improve documentation about node  indexing.
- Add assertation during dataloading
#201
=> Nodes index from 0

.github/workflows/pytest.yml, datasets/ogbn-proteins/task_node_classification_1.json, tests/config.yaml, tests/test_data_loading.py, tests/utils.py
To fix https://github.com/Graph-Learning-Benchmarks/gli/issues/257
add `tests/config.yaml` to store special accommodations
=> Fix test config

gli/tags.py
- Update all the functions to allow sparse matrix manipulation
-  no to_dense needed
=> Update functions related to feature_homogeneity / assortativity

.github/workflows/auto-comment.yml
Add auto comment based on `pull_request_target`. This PR will be merged first to check that whether the workflow can be triggered in coming PR.
=> add auto comment

.github/workflows/auto-comment.yml
=> fix bugs in auto comment

.github/workflows/comment-pr.yml, .github/workflows/receive-pr.yml
For https://github.com/Graph-Learning-Benchmarks/gli/issues/331.
=> new auto comment

.github/workflows/comment-pr.yml, .github/workflows/receive-pr.yml
Test on default setting provided: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
=> change comment test

.github/workflows/test-coment-pr.yml, .github/workflows/test-receive-pr.yml
=> use code in doc for testing

.github/workflows/receive-pr.yml
=> fix echo bugs

gli/tags.py
-Update node label input to numerical form instead of tensor
-Update angular distance computation to allow batch matrix multipulation
=> Modify input form and angular distance function

datasets/actor/actor.ipynb, datasets/actor/metadata.json, datasets/actor/urls.json, datasets/chameleon/chameleon.ipynb, datasets/chameleon/metadata.json, datasets/chameleon/urls.json, datasets/citeseer/citeseer.ipynb, datasets/citeseer/metadata.json, datasets/citeseer/urls.json, datasets/cornell/cornell.ipynb, datasets/cornell/metadata.json, datasets/cornell/urls.json, datasets/squirrel/metadata.json, datasets/squirrel/squirrel.ipynb, datasets/squirrel/urls.json, datasets/texas/metadata.json, datasets/texas/texas.ipynb, datasets/texas/urls.json, datasets/wisconsin/metadata.json, datasets/wisconsin/urls.json, datasets/wisconsin/wisconsin.ipynb, setup.py
Fix datasets npz file.
Fix a bunch of datasets.
issue[#302](https://github.com/Graph-Learning-Benchmarks/gli/issues/302#issuecomment-1272381289)
=> Update datasets storage format

datasets/cifar/README.md, datasets/mnist/README.md
Fix README.md in datasets `cifar` and `mnist`
=> fix cifar mnist README

datasets/chameleon/README.md, datasets/squirrel/README.md
Improve descriptions and the format of README.md files in datasets `squirrel` and `chameleon`.
=> fix readme squirrel chameleon

datasets/cora/LICENSE, datasets/cora/README.md, tests/test_files.py, tests/utils.py
This PR refactors `tests/test_files.py` and add LICENSE and data conversion code as required files. The data conversion code should be named as `<dataset>.ipynb` or `<datas et>.py`.
This PR also adds LICENSE to cora as a test.
We plan to add a LICENSE file for each dataset (see [this comment](https://github.com/Graph-Learning-Benchmarks/gli/issues/327#issuecomment-1295708084) in #327).
=> add test LICENSE and conversion code; refactor test_files.py; add LICENSE to cora

datasets/pubmed/README.md, datasets/squirrel/README.md, datasets/texas/README.md, datasets/wisconsin/README.md
Add LICENSE files and update README.md for datasets `pubmed`, `squirrel`, `texas`, and `wisconsin`.
#327
@StevenGolden1203 will fix the npz files for these 4 datasets.
=> add license for pubmed, squirrel, texas, and wisconsin

gli/tags.py
-update makrdown_file output function
-update all functions to avoid modification of the original graph instance
-remove all testing codes
-remove funcs that cannot run on big datasets
=> Remove redundant comment lines

benchmarks/NodeClassification/configs/catboost.yaml, benchmarks/NodeClassification/configs/lightgbm.yaml, benchmarks/NodeClassification/models/gbdt.py, benchmarks/NodeClassification/train_gbdt.py
As titled.
Can train on Cora now. We don't need to merge this PR until grid search is done.
Sample input:
```
python train_gbdt.py --dataset Cora --model cat boost
```
Sample output:
```
Namespace(model_cfg='configs/model_default.yaml', train_cfg='configs/train_default.yaml', model='catboost', dataset='cora', task='NodeClassification', task_id=1, gpu=-1, verbose=False)
{'num_layers': 1, 'num_hidden': 8, 'dropout': 0.6}
{'loss_fun': 'cross_entropy', 'self_loop': True, 'to_dense': False, 'lr': 0.01, 'weight_decay': 0.001, 'max_epoch': 10000, 'early_stopping': True, 'seed': 0, 'batch_size': 256, 'to_undirected': False, 'optimizer': 'Adam'}
cora NodeClassification 1 5
/Users/jinhuang/Documents/research/gli/gli/utils.py:210: UserWarning: Sparse CSR tensor support is in beta state. If you miss …
```
=> add catboost and lightgbm models&train

datasets/penn94/README.md, datasets/penn94/penn94.ipynb, datasets/penn94/urls.json, datasets/pokec/README.md, datasets/pokec/pokec.ipynb, datasets/pokec/urls.json, datasets/pubmed/metadata.json, datasets/pubmed/pubmed.ipynb, datasets/pubmed/urls.json, datasets/snap-patents/README.md, datasets/snap-patents/snap-patents.ipynb, datasets/snap-patents/urls.json, datasets/twitch-gamers/README.md, datasets/twitch-gamers/twitch-gamers.ipynb, datasets/twitch-gamers/urls.json, datasets/wiki/README.md, datasets/wiki/urls.json, datasets/wiki/wiki.ipynb
=> add pubmed pokec penn94 patent twitch wiki notebook, url, license

gli/dataloading.py
=> fix task name typo in dataloading.py

datasets/chameleon/README.md
=> fix chameleon readme

FORMAT.md
=> add regression task types in FORMAT.md

CODE_OF_CONDUCT.md
=> add code of ethics

CONTRIBUTING.md
=> add data removal policy to CONTRIBUTING.md

benchmarks/GraphClassification/configs/ChebNet.yaml, benchmarks/GraphClassification/configs/DGN.yaml, benchmarks/GraphClassification/configs/model_default.yaml, benchmarks/GraphClassification/models/cheb_net.py, benchmarks/GraphClassification/models/dgn.py, benchmarks/GraphClassification/models/gcn.py, benchmarks/NodeClassification/configs/GraphSAGE.yaml, benchmarks/NodeClassification/configs/MoNet.yaml, benchmarks/NodeClassification/configs/model_default.yaml, benchmarks/NodeClassification/models/gat.py, benchmarks/NodeClassification/models/gcn.py, benchmarks/NodeClassification/models/gcn_minibatch.py, benchmarks/NodeClassification/models/graph_sage.py, benchmarks/NodeClassification/models/monet.py, benchmarks/NodeClassification/train_minibatch.py
Previously, the `num_layer` in config file refers to the number of hidden layers. Now I update the notation so that `num_layer` refers to the total number of layers.
Training can go smoothly on all updated models.
=> update config notation

benchmarks/GraphClassification/README.md, benchmarks/NodeClassification/README.md
=> add readme for benchmarking

tests/test_node_regression_training.py, tests/training_utils.py, tests/utils.py
As titled.
The NodeRegression test can go smoothly on Cora, pretending Cora is a NodeRegession task.
PS: I will open another PR to simply some original code on testing
=> Node regression test

tests/test_kg_training.py, tests/test_node_classification_training.py, tests/training_utils.py
=> simplify test code

datasets/citeseer/README.md, datasets/cora/README.md
=> update citations in cora and citeseer

README.md
=> add paper information

tests/test_files.py
Allow contributions without a task.json file
Change task error to warning. 
#413
=> Allow contributions without a task.json file.

datasets/KGMicrobe/KGMicrobe.ipynb, datasets/KGMicrobe/LICENSE, datasets/KGMicrobe/README.md, datasets/KGMicrobe/metadata.json, datasets/KGMicrobe/urls.json
add KGMicrobe dataset
create KGMicrobe folder in dataset/
None
Enable KGMicrobe dataset
=> add KGMicrobe dataset

gli/utils.py
This PR adds a return object in the function `gli.utils.save_data()`.
We want the contributors to use a function interface to save the graph dataset. `save_data()` will act as a helper function to dump all the data provided from the contributors. Now, the function will return a dictionary which contains the map from `key` (e.g. `'node_list'`) to `location` (e.g. `{'file': 'cora.npz', 'key': 'node_list'}`). A full example is given as below (and also is given in the docstring):
```python
>>> data = {
"node_feats": node_feats,
"node_class": node_class,
"edge": edge,
"node_list": node_list,
"edge_list": edge_list
}
>>> save_data("cora", **data)
{'node_class': {'file': 'cora.npz', 'key': 'node_class'},
'edge': {'file': 'cora.npz', 'key': 'edge'},
'node_list': {'file': 'cora.npz', 'key': …
```
=> Add save_data return

.github/workflows/pytest.yml
Changed `runs-on: ubuntu-20.04` to `runs-on: self-hosted` in pytest.yml to make pytest run on the self-hosted runner.
=> Make pytest run on self-hosted runner

gli/utils.py
- Filename would be in the following formats:
```
{'node_class': {'file': 'cora__b6fadb519365dce6b64a2640bf1df421.npz',
'key': 'node_class'},
'edge': {'file': 'cora__b6fadb519365dce6b64a2640bf1df421.npz', 'key': 'edge'},
'node_list': {'file': 'cora__b6fadb519365dce6b64a2640bf1df421.npz',
'key': 'node_list'},
'edge_list': {'file': 'cora__b6fadb519365dce6b64a2640bf1df421.npz',
'key': 'edge_list'},
'node_feats': {'file': 'cora_node_feats__7032c9c380d1889061dcbbcd76b8c427.sparse.npz'}}
```
Partially fixed #425 
Tested on Cora
=> MD5 unique identifiers for each file

docs/source/_templates/classtemplate.rst, docs/source/api/io.rst, docs/source/generated/gli.dataloading.combine_graph_and_task.rst, docs/source/generated/gli.dataloading.get_gli_graph.rst, docs/source/generated/gli.dataloading.get_gli_task.rst, docs/source/generated/gli.graph.read_gli_graph.rst, docs/source/generated/gli.io.Attribute.rst, docs/source/generated/gli.io.save_graph.rst, docs/source/generated/gli.task.GLITask.rst, docs/source/generated/gli.task.GraphClassificationTask.rst, docs/source/generated/gli.task.GraphRegressionTask.rst, docs/source/generated/gli.task.KGEntityPredictionTask.rst, docs/source/generated/gli.task.KGRelationPredictionTask.rst, docs/source/generated/gli.task.LinkPredictionTask.rst, docs/source/generated/gli.task.NodeClassificationTask.rst, docs/source/generated/gli.task.NodeRegressionTask.rst, docs/source/generated/gli.task.TimeDependentLinkPredictionTask.rst, docs/source/generated/gli.task.read_gli_task.rst, docs/source/index.rst
Added the io doc page.
Tested locally, see screenshots
=> Update io doc

gli/io.py
Refactor `save_task_node_classification` and `save_task_node_regression` to merge the common code into a private function `_save_task_reg_or_cls`.
The examples in the docstring are tested successfully.
=> refactor save regression and classification tasks

docs/source/api/io.rst, docs/source/generated/gli.io.save_heterograph.rst, docs/source/generated/gli.io.save_homograph.rst, gli/graph.py, gli/io.py, tests/test_io.py
This PR implements a new method for contributors to store a heterogeneous graph dataset conveniently.
Here is a detailed walkthrough of this PR:
- (**docs**) Add document for `save_heterograph()`.
- (**tests**) Add tests for `save_homograph()` and `save_heterograph()`.
- `test_save_single_homograph`
- `test_save_multi_homograph`
- `test_save_single_heterograph`
- (**gli.io**) Implement new public method `save_heterograph()`.
- Implement subclass `UniqueID` and `Edges` inherited from `Attribute` (They are used `save_heterograph()` runtime).
- Extract some common methods for saving homo- and hetero-graph (e.g. `_verify_attrs_length`)
- Rename `save_graph()` to `save_homograph()` temporarily.
- Add `num_nodes` as an optional function param for `save_homograph()` like `dgl.graph()`
- Require …
=> Add save method for heterogeneous graph

gli/task.py
`KGRelationPrediction` missed `self.target`, and `KGEntityPrediction` missed `self.predict_tail`. This PR fixed them.
=> add self.target and self.predict_tail

gli/utils.py
Fix minor bug in download_data
=> 🐞 fix(download_data): fix minor bug

benchmarks/GraphClassification/train.py, benchmarks/NodeClassification/train.py, benchmarks/NodeClassification/train_gbdt.py, benchmarks/NodeClassification/train_minibatch.py, gli/utils.py
Fix missing space indicated by pycodestyle test.
=> fix missing space

gli/config.py
My old homepage has been deprecated. So the global_urls.json url in config.py became invalid. This PR updates this url.
=> update global_urls.json url

datasets/citeseer/citeseer.ipynb, datasets/citeseer/metadata.json, datasets/citeseer/task_node_classification_1.json
Made changes to the citeseer dataset using the already updated CORA dataset as reference
* citeseer.ipynb: Replace old methods with the updated function
* .json: Generated automatically.
First step of https://github.com/Graph-Learning-Benchmarks/gli/issues/437. Updating other datasets is in progress.
Tested locally within citeseer.ipynb.
=> updated citeseer

datasets/reddit/LICENSE, datasets/reddit/README.md, datasets/reddit/metadata.json, datasets/reddit/reddit.ipynb, datasets/reddit/task_node_classification_1.json
Add Reddit Dataset available from DGL with Node Classification Task and conveted it into GLI format.
Already run `make pytest DATASET=reddit` locally for Reddit dataset implementation test.
=> Reddit Dataset Contribution
